[workspace]
members = [
	"crates/*",
]

[package]
name = "auxmos"
version = "1.2.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auxcleanup_gas_deletion", "turf_processing"]
auxcleanup_gas_deletion = ["auxcleanup"]
zas_hooks = []
turf_processing = []
equalization = ["turf_processing"]
monstermos = ["equalization"]
putnamos = ["equalization"]
katmos = ["equalization"]
reaction_hooks = []
plasma_fire_hook = ["reaction_hooks"]
trit_fire_hook = ["reaction_hooks"]
fusion_hook = ["reaction_hooks"]
generic_fire_hook = ["reaction_hooks"]
all_reaction_hooks = ["fusion_hook", "trit_fire_hook", "plasma_fire_hook", "generic_fire_hook"]
explosive_decompression = ["monstermos"]
putnamos_decompression = ["putnamos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/willox/auxtools"}
auxcallback = { path = "./crates/auxcallback" }
auxcleanup = { path = "./crates/auxcleanup", optional = true}
itertools = "0.10.5"
rayon = "1.6.1"
float-ord = "0.3.2"
crossbeam = "0.8.1"
flume = "0.10.14"
parking_lot = "0.12.1"
fxhash = "0.2.1"
nonmax = "0.5.3"
ahash = "0.8.3"
lazy_static = "1.4.0"
indexmap = { version = "1.9.2", features = ["rayon"] }
dashmap = { version = "5.4.0", features = ["rayon"] }
atomic_float = "0.1.0"

[dependencies.tinyvec]
version = "1.6.0"
features = ["rustc_1_57", "alloc"]

[profile.release]
lto = 'fat'
debug = true
codegen-units = 1
panic = 'abort'
