name: Build Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target_name: i686-unknown-linux-gnu
            artifact_name: libauxmos.so
          - os: windows-latest
            target_name: i686-pc-windows-msvc
            artifact_name: auxmos.dll
            debug_pdb_name: auxmos.pdb
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Toolchains (Windows)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
        if: matrix.os == 'windows-latest'

      - name: Install g++-multilib
        run: |
          sudo apt update
          sudo apt install g++-multilib -y
        if: matrix.os == 'ubuntu-20.04'

      - name: Setup Toolchains (Ubuntu)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
        if: matrix.os == 'ubuntu-20.04'

      - name: Build auxmos (Windows)
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --target i686-pc-windows-msvc --release --features "all_reaction_hooks katmos"
        if: matrix.os == 'windows-latest'

      - name: Build auxmos (Ubuntu)
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --target i686-unknown-linux-gnu --release --features "all_reaction_hooks katmos"
        if: matrix.os == 'ubuntu-20.04'

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target_name }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}

      - name: Upload debug informations to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target_name }}/release/${{ matrix.debug_pdb_name }}
          asset_name: ${{ matrix.debug_pdb_name }}
          tag: ${{ github.ref }}
        if: matrix.os == 'windows-latest'
